move types from global.d.ts to ts files
site-bender/fp pull request #1
Opened 2024-04-11 23:41 UTC by benjstephenson

2024-04-11 23:45 UTC, chasm requested changes

2024-04-11 23:45 UTC, chasm commented on vite.config.js
> +	],
You don't need the vitest-localstorage-mock bit (or the library). No need to mock local or seesion storage in the fp module, only in operations.

2024-04-11 23:51 UTC, benjstephenson commented on vite.config.js
> +	],
removed the mock.  Updated the library to be @sitebender/fp, if I remove it then vite complains it can't find index.html and fails to build

2024-04-12 00:13 UTC, chasm approved these changes

2024-04-12 00:13 UTC, merged